name: flutter_login
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.17.4
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  share: ^0.6.0+1
  fluttertoast: ^3.0.4
  avatar_glow: ^0.1.0
  bottom_navy_bar: ^3.0.0
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
